# Data Cleaning

In [2]:
import pandas as pd

In [4]:
mvps = pd.read_csv("mvps.csv")

In [6]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77,891,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10,497,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6,476,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2,222,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0,142,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,10,11,Russell Westbrook,32,WAS,0,5,1010,0.005,65,...,11.5,11.7,1.4,0.4,0.439,0.315,0.656,3.7,0.075,2021
470,11,12,Ben Simmons,24,PHI,0,3,1010,0.003,58,...,7.2,6.9,1.6,0.6,0.557,0.300,0.613,6.0,0.153,2021
471,12,13T,James Harden,31,TOT,0,1,1010,0.001,44,...,7.9,10.8,1.2,0.8,0.466,0.362,0.861,7.0,0.208,2021
472,13,13T,LeBron James,36,LAL,0,1,1010,0.001,45,...,7.7,7.8,1.1,0.6,0.513,0.365,0.698,5.6,0.179,2021
473,14,13T,Kawhi Leonard,29,LAC,0,1,1010,0.001,52,...,6.5,5.2,1.6,0.4,0.512,0.398,0.885,8.8,0.238,2021

In [8]:
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]

In [10]:
mvps

                Player  Year  Pts Won  Pts Max  Share
0       Michael Jordan  1991      891      960  0.928
1        Magic Johnson  1991      497      960  0.518
2       David Robinson  1991      476      960  0.496
3      Charles Barkley  1991      222      960  0.231
4          Karl Malone  1991      142      960  0.148
..                 ...   ...      ...      ...    ...
469  Russell Westbrook  2021        5     1010  0.005
470        Ben Simmons  2021        3     1010  0.003
471       James Harden  2021        1     1010  0.001
472       LeBron James  2021        1     1010  0.001
473      Kawhi Leonard  2021        1     1010  0.001

[474 rows x 5 columns]

In [12]:
players = pd.read_csv("players.csv")

In [14]:
players

,Unnamed: 0,Rk,Player,Age,Team,Pos,G,GS,MP,FG,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,0,1,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,...,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,"MVP-1,DPOY-7,AS,NBA1",1991
1,1,2,Karl Malone,27,UTA,PF,82,82,40.3,10.3,...,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,"MVP-5,AS,NBA1",1991
2,2,3,Bernard King,34,WSB,SF,64,64,37.5,11.1,...,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,"MVP-16,AS,NBA3",1991
3,3,4,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,...,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,"MVP-4,AS,NBA1",1991
4,4,5,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,...,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,"MVP-11,DPOY-7,AS,NBA2",1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17940,723,537,Will Magnay,22,NOP,C,1,0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN,2021
17941,724,538,Anžejs Pasečņiks,25,WAS,C,1,0,6.0,0.0,...,0.0,1.0,1.0,0.0,0.0,5.0,2.0,0.0,NaN,2021
17942,725,539,Noah Vonleh,25,BRK,C,4,0,2.8,0.0,...,0.3,0.3,0.3,0.0,0.0,0.5,0.5,0.0,NaN,2021
17943,726,540,Greg Whittington,27,DEN,PF,4,0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2021
17944,727,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021

In [16]:
del players["Unnamed: 0"]

In [18]:
del players["Rk"]

In [20]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,22.4,.539,...,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,"MVP-1,DPOY-7,AS,NBA1",1991
1,Karl Malone,27,UTA,PF,82,82,40.3,10.3,19.6,.527,...,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,"MVP-5,AS,NBA1",1991
2,Bernard King,34,WSB,SF,64,64,37.5,11.1,23.6,.472,...,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,"MVP-16,AS,NBA3",1991
3,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,17.4,.570,...,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,"MVP-4,AS,NBA1",1991
4,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,20.3,.514,...,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,"MVP-11,DPOY-7,AS,NBA2",1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17940,Will Magnay,22,NOP,C,1,0,3.0,0.0,1.0,.000,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN,2021
17941,Anžejs Pasečņiks,25,WAS,C,1,0,6.0,0.0,1.0,.000,...,0.0,1.0,1.0,0.0,0.0,5.0,2.0,0.0,NaN,2021
17942,Noah Vonleh,25,BRK,C,4,0,2.8,0.0,0.8,.000,...,0.3,0.3,0.3,0.0,0.0,0.5,0.5,0.0,NaN,2021
17943,Greg Whittington,27,DEN,PF,4,0,3.0,0.0,0.8,.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2021
17944,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021

In [22]:
players.head(20)

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,22.4,.539,...,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,"MVP-1,DPOY-7,AS,NBA1",1991
1,Karl Malone,27,UTA,PF,82,82,40.3,10.3,19.6,.527,...,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,"MVP-5,AS,NBA1",1991
2,Bernard King,34,WSB,SF,64,64,37.5,11.1,23.6,.472,...,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,"MVP-16,AS,NBA3",1991
3,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,17.4,.570,...,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,"MVP-4,AS,NBA1",1991
4,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,20.3,.514,...,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,"MVP-11,DPOY-7,AS,NBA2",1991
5,Michael Adams,28,DEN,PG,66,66,35.5,8.5,21.5,.394,...,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,NaN,1991
6,Dominique Wilkins,31,ATL,SF,81,81,38.0,9.5,20.2,.470,...,5.8,9.0,3.3,1.5,0.8,2.5,1.9,25.9,"MVP-8,AS,NBA2",1991
7,Chris Mullin,27,GSW,SF,82,82,40.4,9.5,17.7,.536,...,3.7,5.4,4.0,2.1,0.8,3.0,2.1,25.7,"AS,NBA2",1991
8,David Robinson,25,SAS,C,82,81,37.7,9.2,16.7,.552,...,8.9,13.0,2.5,1.5,3.9,3.3,3.2,25.6,"MVP-3,DPOY-2,AS,NBA1",1991
9,Orlando Woolridge,31,DEN,SF,53,50,34.4,9.2,18.5,.498,...,4.2,6.8,2.2,1.3,0.4,2.9,2.7,25.1,NaN,1991
10,Mitch Richmond,25,GSW,SG,77,77,39.3,9.1,18.5,.494,...,4.0,5.9,3.1,1.6,0.4,3.0,2.7,23.9,NaN,1991
11,Tim Hardaway,24,GSW,PG,82,82,39.2,9.0,18.9,.476,...,3.0,4.0,9.7,2.6,0.1,3.3,2.8,22.9,"MVP-19,AS",1991
12,Reggie Miller,25,IND,SG,82,82,36.2,7.3,14.2,.512,...,2.4,3.4,4.0,1.3,0.2,2.0,2.0,22.6,NaN,1991
13,Kevin Johnson,24,PHO,PG,77,76,36.0,7.7,14.9,.516,...,2.8,3.5,10.1,2.1,0.1,3.5,2.3,22.2,"MVP-7,AS,NBA2",1991
14,Hersey Hawkins,24,PHI,SG,80,80,38.9,7.4,15.6,.472,...,3.3,3.9,3.7,2.2,0.5,2.7,2.3,22.1,AS,1991
15,Tony Campbell,28,MIN,SG,77,71,37.6,8.5,19.5,.434,...,2.4,4.5,2.8,1.6,0.6,2.5,2.6,21.8,NaN,1991
16,Brad Daugherty,25,CLE,C,76,76,38.8,8.0,15.2,.524,...,8.6,10.9,3.3,1.0,0.6,2.8,2.5,21.6,AS,1991
17,Clyde Drexler,28,POR,SG,82,82,34.8,7.9,16.3,.482,...,4.1,6.7,6.0,1.8,0.7,2.8,2.8,21.5,"MVP-6,AS,NBA2",1991
18,James Worthy,29,LAL,SF,78,74,38.6,9.2,18.7,.492,...,3.2,4.6,3.5,1.3,0.4,1.6,1.5,21.4,"AS,NBA3",1991
19,Hakeem Olajuwon,28,HOU,C,56,50,36.8,8.7,17.1,.508,...,9.8,13.8,2.3,2.2,3.9,3.1,3.9,21.2,"MVP-18,DPOY-5,NBA3",1991

In [24]:
players.groupby(["Player", "Year"])

In [26]:
def single_row(df):
    if df.shape[0]== 1:
        return df
    else:
        row = df[df["Team"] == "TOT"]
        row["Team"] = df.iloc[-1,:]["Team"]
        return row

players = players.groupby(["Player", "Year"]).apply(single_row)

/tmp/ipykernel_85913/79905288.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  players = players.groupby(["Player", "Year"]).apply(single_row)

In [27]:
import pandas as pd; print(pd.__version__)

2.2.3

In [30]:
players.head(20)

                                 Player Age Team Pos   G  GS    MP   FG   FGA  \
Player        Year
A.C. Green    1991 182       A.C. Green  27  LAL  PF  82  21  26.4  3.1   6.6
              1992 550       A.C. Green  28  LAL  PF  82  53  35.4  4.7   9.8
              1993 1035      A.C. Green  29  LAL  PF  82  55  34.4  4.6   8.6
              1994 1465      A.C. Green  30  PHO  PF  82  55  34.5  5.7  11.3
              1995 2021      A.C. Green  31  PHO  SF  82  52  32.8  3.8   7.5
              1996 2601      A.C. Green  32  PHO  SF  82  36  25.8  2.6   5.4
              1998 3759      A.C. Green  34  DAL  PF  82  68  32.3  3.0   6.5
              1999 4377      A.C. Green  35  DAL  PF  50  35  18.5  2.2   5.1
              2000 4907      A.C. Green  36  LAL  PF  82  82  23.5  2.1   4.7
              2001 5466      A.C. Green  37  MIA  PF  82   1  17.2  1.8   4.0
A.J. Bramlett 2000 5084   A.J. Bramlett  23  CLE   C   8   0   7.6  0.5   2.6
A.J. English  1991 187     A.J. English  23  WSB  SG  70  12  20.6  3.6   8.2
              1992 593     A.J. English  24  WSB  SG  81   6  20.6  4.5  10.4
A.J. Guyton   2001 5381     A.J. Guyton  22  CHI  PG  33   8  19.1  2.4   5.8
              2002 5955     A.J. Guyton  23  CHI  PG  45   6  13.5  2.0   5.4
              2003 6669     A.J. Guyton  24  GSW  PG   2   0   4.5  0.0   2.0
A.J. Hammons  2017 15078   A.J. Hammons  24  DAL   C  22   0   7.4  0.8   1.9
A.J. Price    2010 10504     A.J. Price  23  IND  PG  56   2  15.4  2.6   6.3
              2011 11138     A.J. Price  24  IND  PG  50   0  15.9  2.3   6.4
              2012 11854     A.J. Price  25  IND  PG  44   1  12.9  1.3   4.0

                           FG%  ...  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  \
Player        Year              ...
A.C. Green    1991 182    .476  ...  3.8  6.3  0.9  0.7  0.3  1.2  1.4   9.1
              1992 550    .476  ...  5.6  9.3  1.4  1.1  0.4  1.4  1.7  13.6
              1993 1035   .537  ...  5.2  8.7  1.4  1.1  0.5  1.4  1.8  12.8
              1994 1465   .502  ...  5.8  9.2  1.7  0.9  0.5  1.2  1.7  14.7
              1995 2021   .504  ...  5.8  8.2  1.5  0.7  0.4  1.4  1.8  11.2
              1996 2601   .484  ...  4.7  6.8  0.9  0.5  0.3  1.0  1.7   7.5
              1998 3759   .453  ...  5.5  8.1  1.5  1.0  0.3  0.8  1.9   7.3
              1999 4377   .422  ...  2.9  4.6  0.5  0.6  0.2  0.4  1.4   4.9
              2000 4907   .447  ...  4.0  5.9  1.0  0.6  0.2  0.6  1.5   5.0
              2001 5466   .444  ...  2.5  3.8  0.5  0.4  0.1  0.5  1.5   4.5
A.J. Bramlett 2000 5084   .190  ...  1.3  2.8  0.0  0.1  0.0  0.4  1.6   1.0
A.J. English  1991 187    .439  ...  1.2  2.1  2.5  0.4  0.2  1.6  1.8   8.8
              1992 593    .433  ...  1.2  2.1  1.8  0.4  0.1  1.1  2.0  10.9
A.J. Guyton   2001 5381   .406  ...  0.8  1.1  1.9  0.3  0.2  0.7  1.1   6.0
              2002 5955   .361  ...  0.7  1.0  1.8  0.2  0.2  0.8  0.5   5.4
              2003 6669   .000  ...  0.0  0.0  1.0  0.5  0.0  0.5  0.0   0.0
A.J. Hammons  2017 15078  .405  ...  1.3  1.6  0.2  0.0  0.6  0.5  1.0   2.2
A.J. Price    2010 10504  .410  ...  1.4  1.6  1.9  0.6  0.1  1.1  0.9   7.3
              2011 11138  .356  ...  1.1  1.4  2.2  0.6  0.0  1.1  1.2   6.5
              2012 11854  .339  ...  1.1  1.4  2.0  0.5  0.0  0.7  0.7   3.9

                         Awards  Year
Player        Year
A.C. Green    1991 182      NaN  1991
              1992 550      NaN  1992
              1993 1035     NaN  1993
              1994 1465     NaN  1994
              1995 2021     NaN  1995
              1996 2601     NaN  1996
              1998 3759     NaN  1998
              1999 4377     NaN  1999
              2000 4907     NaN  2000
              2001 5466     NaN  2001
A.J. Bramlett 2000 5084     NaN  2000
A.J. English  1991 187      NaN  1991
              1992 593      NaN  1992
A.J. Guyton   2001 5381     NaN  2001
              2002 5955     NaN  2002
              2003 6669     NaN  2003
A.J. Hammons  2017 15078    NaN  2017
A.J. Price    2010 10504    NaN  2010
              2011 11138    NaN  2011
              2012 11854    NaN  2012

[20 rows x 31 columns]

In [32]:
players.index = players.index.droplevel()
players.index = players.index.droplevel()

In [34]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
182,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,NaN,1991
550,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,NaN,1992
1035,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,NaN,1993
1465,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,NaN,1994
2021,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,NaN,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8296,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,1.2,1.8,0.3,0.2,0.1,0.6,1.4,3.3,NaN,2006
5903,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,NaN,2002
6405,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,NaN,2003
7611,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,NaN,2005
8224,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,NaN,2006

In [36]:
players[players["Player"] == "Ricky Pierce"]

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
466,Ricky Pierce,32,SEA,SG,78,78,34.1,7.9,16.7,.475,...,1.8,3.0,3.1,1.1,0.3,2.4,2.7,21.7,NaN,1992
961,Ricky Pierce,33,SEA,SG,77,72,28.8,6.8,13.9,.489,...,1.7,2.5,2.9,1.3,0.1,2.1,2.2,18.2,NaN,1993
1467,Ricky Pierce,34,SEA,SG,51,0,20.0,5.3,11.3,.471,...,1.1,1.6,1.8,0.8,0.1,1.3,1.6,14.5,6MOY-4,1994
2005,Ricky Pierce,35,GSW,PG,27,6,24.9,4.1,9.4,.437,...,1.9,2.4,1.5,0.8,0.1,0.9,1.4,12.5,NaN,1995
2551,Ricky Pierce,36,IND,SG,76,2,18.5,3.5,7.8,.447,...,1.3,1.8,1.3,0.8,0.1,1.2,2.5,9.7,NaN,1996
3895,Ricky Pierce,38,MIL,SG,39,0,11.3,1.3,3.7,.364,...,0.7,1.2,0.9,0.2,0.0,0.5,0.9,3.9,NaN,1998

In [38]:
combined = players.merge(mvps, how="outer", on=["Player", "Year"])

In [40]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,NaN,1991,NaN,NaN,NaN
1,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,NaN,1992,NaN,NaN,NaN
2,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,NaN,1993,NaN,NaN,NaN
3,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,NaN,1994,NaN,NaN,NaN
4,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,NaN,1995,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12550,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.2,0.1,0.6,1.4,3.3,NaN,2006,NaN,NaN,NaN
12551,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,0.4,1.0,1.1,2.6,6.9,NaN,2002,NaN,NaN,NaN
12552,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.2,0.6,1.0,2.6,6.6,NaN,2003,NaN,NaN,NaN
12553,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.2,0.7,0.8,2.2,5.8,NaN,2005,NaN,NaN,NaN
12554,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.2,0.7,0.8,2.0,4.7,NaN,2006,NaN,NaN,NaN

In [42]:
combined[combined["Pts Won"] > 0]

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
162,Al Jefferson,29,CHA,C,73,73,35.0,9.6,18.8,.509,...,0.9,1.1,1.7,2.4,21.8,"MVP-8,NBA3",2014,34.0,1250.0,0.027
287,Allen Iverson,21,PHI,PG,76,74,40.1,8.2,19.8,.416,...,2.1,0.3,4.4,3.1,23.5,"MVP-17,ROY-1",1997,1.0,1150.0,0.001
289,Allen Iverson,23,PHI,SG,48,48,41.5,9.1,22.0,.412,...,2.3,0.1,3.5,2.0,26.8,"MVP-4,NBA1",1999,319.0,1180.0,0.270
290,Allen Iverson,24,PHI,SG,70,70,40.8,10.4,24.8,.421,...,2.1,0.1,3.3,2.3,28.4,"MVP-7,AS,NBA2",2000,132.0,1210.0,0.109
291,Allen Iverson,25,PHI,SG,71,71,42.0,10.7,25.5,.420,...,2.5,0.3,3.3,2.1,31.1,"MVP-1,DPOY-11,AS,NBA1",2001,1121.0,1240.0,0.904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12105,Vince Carter,23,TOR,SF,82,82,38.1,9.6,20.7,.465,...,1.3,1.1,2.2,3.2,25.7,"MVP-10,AS,NBA3",2000,51.0,1210.0,0.042
12106,Vince Carter,24,TOR,SF,75,75,39.7,10.2,22.1,.460,...,1.5,1.1,2.2,2.7,27.6,"MVP-11,AS,NBA2",2001,7.0,1240.0,0.006
12110,Vince Carter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2005,3.0,1270.0,0.002
12426,Yao Ming,23,HOU,C,82,82,32.8,6.5,12.5,.522,...,0.3,1.9,2.5,3.3,17.5,"MVP-14,AS,NBA3",2004,1.0,1230.0,0.001
12431,Yao Ming,28,HOU,C,77,77,33.6,7.4,13.4,.548,...,0.4,1.9,3.0,3.3,19.7,"MVP-12,AS,NBA2",2009,1.0,1210.0,0.001

In [44]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [46]:
combined[combined["Pts Won"] > 0]

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
162,Al Jefferson,29,CHA,C,73,73,35.0,9.6,18.8,.509,...,0.9,1.1,1.7,2.4,21.8,"MVP-8,NBA3",2014,34.0,1250.0,0.027
287,Allen Iverson,21,PHI,PG,76,74,40.1,8.2,19.8,.416,...,2.1,0.3,4.4,3.1,23.5,"MVP-17,ROY-1",1997,1.0,1150.0,0.001
289,Allen Iverson,23,PHI,SG,48,48,41.5,9.1,22.0,.412,...,2.3,0.1,3.5,2.0,26.8,"MVP-4,NBA1",1999,319.0,1180.0,0.270
290,Allen Iverson,24,PHI,SG,70,70,40.8,10.4,24.8,.421,...,2.1,0.1,3.3,2.3,28.4,"MVP-7,AS,NBA2",2000,132.0,1210.0,0.109
291,Allen Iverson,25,PHI,SG,71,71,42.0,10.7,25.5,.420,...,2.5,0.3,3.3,2.1,31.1,"MVP-1,DPOY-11,AS,NBA1",2001,1121.0,1240.0,0.904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12105,Vince Carter,23,TOR,SF,82,82,38.1,9.6,20.7,.465,...,1.3,1.1,2.2,3.2,25.7,"MVP-10,AS,NBA3",2000,51.0,1210.0,0.042
12106,Vince Carter,24,TOR,SF,75,75,39.7,10.2,22.1,.460,...,1.5,1.1,2.2,2.7,27.6,"MVP-11,AS,NBA2",2001,7.0,1240.0,0.006
12110,Vince Carter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2005,3.0,1270.0,0.002
12426,Yao Ming,23,HOU,C,82,82,32.8,6.5,12.5,.522,...,0.3,1.9,2.5,3.3,17.5,"MVP-14,AS,NBA3",2004,1.0,1230.0,0.001
12431,Yao Ming,28,HOU,C,77,77,33.6,7.4,13.4,.548,...,0.4,1.9,3.0,3.3,19.7,"MVP-12,AS,NBA2",2009,1.0,1210.0,0.001

In [48]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,NaN,1991,0.0,0.0,0.0
1,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,NaN,1992,0.0,0.0,0.0
2,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,NaN,1993,0.0,0.0,0.0
3,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,NaN,1994,0.0,0.0,0.0
4,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,NaN,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12550,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.2,0.1,0.6,1.4,3.3,NaN,2006,0.0,0.0,0.0
12551,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,0.4,1.0,1.1,2.6,6.9,NaN,2002,0.0,0.0,0.0
12552,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.2,0.6,1.0,2.6,6.6,NaN,2003,0.0,0.0,0.0
12553,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.2,0.7,0.8,2.2,5.8,NaN,2005,0.0,0.0,0.0
12554,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.2,0.7,0.8,2.0,4.7,NaN,2006,0.0,0.0,0.0

In [50]:
teams = pd.read_csv("teams.csv")

In [52]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
14,0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1991,Midwest Division
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
22,8,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,1991,Pacific Division
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings

In [54]:
teams = teams[~teams["W"].str.contains("Division")]

In [56]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings
30,0,51,31,.622,—,106.6,103.0,3.41,1992,Boston Celtics*
31,1,51,31,.622,—,101.6,97.7,3.67,1992,New York Knicks*
32,2,40,42,.488,11.0,105.4,107.1,-1.54,1992,New Jersey Nets*

In [58]:
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

In [60]:
teams.head(5)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets

In [62]:
teams["Team"].unique()

array(['Boston Celtics', 'Philadelphia 76ers', 'New York Knicks',
       'Washington Bullets', 'New Jersey Nets', 'Miami Heat',
       'Chicago Bulls', 'Detroit Pistons', 'Milwaukee Bucks',
       'Atlanta Hawks', 'Indiana Pacers', 'Cleveland Cavaliers',
       'Charlotte Hornets', 'San Antonio Spurs', 'Utah Jazz',
       'Houston Rockets', 'Orlando Magic', 'Minnesota Timberwolves',
       'Dallas Mavericks', 'Denver Nuggets', 'Portland Trail Blazers',
       'Los Angeles Lakers', 'Phoenix Suns', 'Golden State Warriors',
       'Seattle SuperSonics', 'Los Angeles Clippers', 'Sacramento Kings',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [64]:
combined["Team"].unique()

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'CHI', 'GSW', 'IND',
       'WAS', 'MIN', 'BOS', 'HOU', 'ORL', 'NOH', 'TOR', 'CHO', 'POR',
       'PHI', 'UTA', 'MIL', 'SEA', 'NJN', 'LAC', 'OKC', 'ATL', 'CHA',
       'DEN', 'NYK', 'NOP', 'BRK', 'DET', 'SAS', 'MEM', 'CHH', 'SAC',
       'VAN', 'NOK', nan], dtype=object)

In [71]:
nicknames = {}

with open("nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev,name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

In [73]:
nicknames

{'ATL': 'Atlanta Hawks',
 'BRK': 'Brooklyn Nets',
 'BKN': 'Brooklyn Nets',
 'BOS': 'Boston Celtics',
 'CHA': 'Charlotte Bobcats',
 'CHH': 'Charlotte Hornets',
 'CHO': 'Charlotte Hornets',
 'CHI': 'Chicago Bulls',
 'CLE': 'Cleveland Cavaliers',
 'DAL': 'Dallas Mavericks',
 'DEN': 'Denver Nuggets',
 'DET': 'Detroit Pistons',
 'GSW': 'Golden State Warriors',
 'HOU': 'Houston Rockets',
 'IND': 'Indiana Pacers',
 'LAC': 'Los Angeles Clippers',
 'LAL': 'Los Angeles Lakers',
 'MEM': 'Memphis Grizzlies',
 'MIA': 'Miami Heat',
 'MIL': 'Milwaukee Bucks',
 'MIN': 'Minnesota Timberwolves',
 'NJN': 'New Jersey Nets',
 'NOH': 'New Orleans Hornets',
 'NOP': 'New Orleans Pelicans',
 'NOK': 'New Orleans/Oklahoma City Hornets',
 'NYK': 'New York Knicks',
 'OKC': 'Oklahoma City Thunder',
 'ORL': 'Orlando Magic',
 'PHI': 'Philadelphia 76ers',
 'PHX': 'Phoenix Suns',
 'PHO': 'Phoenix Suns',
 'POR': 'Portland Trail Blazers',
 'SEA': 'Seattle SuperSonics',
 'SAC': 'Sacramento Kings',
 'SAS': 'San Antonio Spurs',
 'TOR': 'Toronto Raptors',
 'UTA': 'Utah Jazz',
 'VAN': 'Vancouver Grizzlies',
 'WAS': 'Washington Wizards',
 'WSB': 'Washington Bullets'}

In [81]:
combined["Team"] = combined["Team"].map(nicknames)

In [83]:
combined.head()

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,Los Angeles Lakers,PF,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,NaN,1991,0.0,0.0,0.0
1,A.C. Green,28,Los Angeles Lakers,PF,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,NaN,1992,0.0,0.0,0.0
2,A.C. Green,29,Los Angeles Lakers,PF,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,NaN,1993,0.0,0.0,0.0
3,A.C. Green,30,Phoenix Suns,PF,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,NaN,1994,0.0,0.0,0.0
4,A.C. Green,31,Phoenix Suns,SF,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,NaN,1995,0.0,0.0,0.0

In [87]:
del combined["Awards"]

In [117]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,Los Angeles Lakers,PF,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,28,Los Angeles Lakers,PF,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,29,Los Angeles Lakers,PF,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,30,Phoenix Suns,PF,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,31,Phoenix Suns,SF,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12550,Žarko Čabarkapa,24,Golden State Warriors,PF,61,0,8.3,1.1,2.9,.385,...,0.3,0.2,0.1,0.6,1.4,3.3,2006,0.0,0.0,0.0
12551,Željko Rebrača,29,Detroit Pistons,C,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
12552,Željko Rebrača,30,Detroit Pistons,C,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
12553,Željko Rebrača,32,Los Angeles Clippers,C,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
12554,Željko Rebrača,33,Los Angeles Clippers,C,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [123]:
combined[combined["Player"] == "Derrick Rose"]

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
3269,Derrick Rose,20,Chicago Bulls,PG,81,80,37.0,7.1,14.9,.475,...,6.3,0.8,0.2,2.5,1.5,16.8,2009,0.0,0.0,0.000
3270,Derrick Rose,21,Chicago Bulls,PG,78,78,36.8,8.6,17.6,.489,...,6.0,0.7,0.3,2.8,1.2,20.8,2010,0.0,0.0,0.000
3271,Derrick Rose,22,Chicago Bulls,PG,81,81,37.4,8.8,19.7,.445,...,7.7,1.0,0.6,3.4,1.7,25.0,2011,1182.0,1210.0,0.977
3272,Derrick Rose,23,Chicago Bulls,PG,39,39,35.3,7.7,17.8,.435,...,7.9,0.9,0.7,3.1,1.3,21.8,2012,5.0,1210.0,0.004
3273,Derrick Rose,25,Chicago Bulls,PG,10,10,31.1,5.8,16.4,.354,...,4.3,0.5,0.1,3.4,1.5,15.9,2014,0.0,0.0,0.000
3274,Derrick Rose,26,Chicago Bulls,PG,51,51,30.0,6.6,16.4,.405,...,4.9,0.7,0.3,3.2,1.2,17.7,2015,0.0,0.0,0.000
3275,Derrick Rose,27,Chicago Bulls,PG,66,66,31.8,6.8,15.9,.427,...,4.7,0.7,0.2,2.7,1.3,16.4,2016,0.0,0.0,0.000
3276,Derrick Rose,28,New York Knicks,PG,64,64,32.5,7.2,15.3,.471,...,4.4,0.7,0.3,2.3,1.3,18.0,2017,0.0,0.0,0.000
3277,Derrick Rose,30,Minnesota Timberwolves,PG,51,13,27.3,7.1,14.8,.482,...,4.3,0.6,0.2,1.6,1.1,18.0,2019,0.0,0.0,0.000
3278,Derrick Rose,31,Detroit Pistons,PG,50,15,26.0,7.4,15.1,.490,...,5.6,0.8,0.3,2.5,1.0,18.1,2020,0.0,0.0,0.000
3279,Derrick Rose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,10.0,1010.0,0.010

In [91]:
stats = combined.merge(teams, how="outer", on=["Team", "Year"])

In [93]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Doc Rivers,29,Atlanta Hawks,PG,79,79,32.7,5.6,12.9,.435,...,0.0,0.000,10.0,43,39,.524,18.0,109.8,109.0,0.72
1,Dominique Wilkins,31,Atlanta Hawks,SF,81,81,38.0,9.5,20.2,.470,...,960.0,0.030,10.0,43,39,.524,18.0,109.8,109.0,0.72
2,Duane Ferrell,25,Atlanta Hawks,SF,78,2,14.9,2.2,4.6,.489,...,0.0,0.000,10.0,43,39,.524,18.0,109.8,109.0,0.72
3,Gary Leonard,23,Atlanta Hawks,C,4,0,2.3,0.0,0.0,NaN,...,0.0,0.000,10.0,43,39,.524,18.0,109.8,109.0,0.72
4,John Battle,28,Atlanta Hawks,SG,79,2,23.6,5.0,10.9,.461,...,0.0,0.000,10.0,43,39,.524,18.0,109.8,109.0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12550,Derrick Rose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1010.0,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12551,James Harden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1010.0,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12552,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.466,...,0.0,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12553,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1010.0,0.042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12554,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1010.0,0.961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [132]:
stats[stats["Player"] == "Luka DonÄiÄ"].Year

12548    2020
12553    2021
Name: Year, dtype: int64

In [95]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,Los Angeles Lakers,PF,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,28,Los Angeles Lakers,PF,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,29,Los Angeles Lakers,PF,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,30,Phoenix Suns,PF,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,31,Phoenix Suns,SF,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12550,Žarko Čabarkapa,24,Golden State Warriors,PF,61,0,8.3,1.1,2.9,.385,...,0.3,0.2,0.1,0.6,1.4,3.3,2006,0.0,0.0,0.0
12551,Željko Rebrača,29,Detroit Pistons,C,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
12552,Željko Rebrača,30,Detroit Pistons,C,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
12553,Željko Rebrača,32,Los Angeles Clippers,C,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
12554,Željko Rebrača,33,Los Angeles Clippers,C,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [97]:
del stats["Unnamed: 0"]

In [99]:
stats.dtypes

Player      object
Age         object
Team        object
Pos         object
G           object
GS          object
MP          object
FG          object
FGA         object
FG%         object
3P          object
3PA         object
3P%         object
2P          object
2PA         object
2P%         object
eFG%        object
FT          object
FTA         object
FT%         object
ORB         object
DRB         object
TRB         object
AST         object
STL         object
BLK         object
TOV         object
PF          object
PTS         object
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
W           object
L           object
W/L%        object
GB          object
PS/G        object
PA/G        object
SRS         object
dtype: object

In [101]:
stats.tail()

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Pts Won,Pts Max,Share,W,L,W/L%,GB,PS/G,PA/G,SRS
12550,Derrick Rose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,1010.0,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12551,James Harden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1010.0,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12552,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.466,...,0.0,0.0,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12553,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42.0,1010.0,0.042,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12554,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,971.0,1010.0,0.961,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
stats["Player"].tail()

12550      Derrick Rose
12551      James Harden
12552    League Average
12553     Luka DonÄiÄ
12554     Nikola JokiÄ
Name: Player, dtype: object

In [113]:
stats["Year"].tail()

12550    2021
12551    2021
12552    2021
12553    2021
12554    2021
Name: Year, dtype: int64